/**
 * The theme contract: every token the library paints with, its default (the
 * design system's app surface), the custom-property names that fill it in an uploaded design
 * system, the component it is read from when no name matches, and how a
 * missing colour is derived. The /theme page renders this list as its "what
 * the file must define" table and builds its editor from it, so editing it
 * edits both. `tests/theme-import.test.ts` checks every default against
 * quebi-theme.css.
 */
import { type Lookup, luminance, mix, type TokenSpec, withAlpha } from "@/site/theme-color"
import { SHAPE_AND_TYPE_TOKENS } from "@/site/theme-tokens-shape"

const isDark = (get: Lookup) => luminance(get("bg")) < 0.2

export const TOKENS: TokenSpec[] = [
  // ---- grounds --------------------------------------------------------------
  {
    key: "bg",
    target: "--q-bg",
    kind: "color",
    group: "ground",
    names: ["app-bg", "bg-000", "bg", "background", "color-bg", "color-background", "surface", "page"],
    role: "Page ground. Everything sits on it.",
    required: true,
    perTheme: true,
    default: { light: "#ffffff", dark: "#111827" },
    probe: "background of a `*-page` class",
  },
  {
    key: "fg",
    target: "--q-fg",
    kind: "color",
    group: "ink",
    names: ["app-text", "text", "fg", "foreground", "color-text", "color-fg", "ink"],
    role: "Headlines, navigation, links, primary copy.",
    required: true,
    perTheme: true,
    default: { light: "#030712", dark: "#f9fafb" },
  },
  {
    key: "fg-muted",
    target: "--q-fg-muted",
    kind: "color",
    group: "ink",
    names: ["app-text-2", "text-body", "fg-muted", "text-secondary", "color-text-secondary", "body"],
    role: "Running text.",
    perTheme: true,
    default: { light: "#374151", dark: "#d1d5db" },
    fallback: { note: "fg", derive: (get) => get("fg") },
  },
  {
    key: "fg-subtle",
    target: "--q-fg-subtle",
    kind: "color",
    group: "ink",
    names: ["app-text-muted", "text-muted", "fg-subtle", "text-tertiary", "muted", "color-text-muted"],
    role: "Labels, captions, numbers, placeholders.",
    perTheme: true,
    default: { light: "#5b6472", dark: "#9ca3af" },
    fallback: { note: "fg mixed 68% into bg", derive: (get) => mix(get("fg"), get("bg"), 0.68) },
  },
  {
    key: "raised",
    target: "--q-raised",
    kind: "color",
    group: "ground",
    names: ["app-surface", "bg-100", "bg-raised", "surface-raised", "bg-subtle", "surface-2"],
    role: "Hovered rows, tags, inset areas.",
    perTheme: true,
    default: { light: "#f3f4f6", dark: "#182131" },
    fallback: { note: "fg mixed 10% into bg", derive: (get) => mix(get("fg"), get("bg"), 0.1) },
  },
  {
    key: "pressed",
    target: "--q-pressed",
    kind: "color",
    group: "ground",
    names: ["app-line", "bg-200", "bg-pressed", "surface-pressed", "surface-3"],
    role: "Pressed states, a second level on raised.",
    perTheme: true,
    default: { light: "#e5e7eb", dark: "#273142" },
    fallback: { note: "fg mixed 15% into bg", derive: (get) => mix(get("fg"), get("bg"), 0.15) },
  },
  {
    key: "card",
    target: "--q-card",
    kind: "color",
    group: "ground",
    names: ["card", "bg-card", "surface-card", "bg-box"],
    role: "The ground of a card, and of a boxed field.",
    perTheme: true,
    default: "var(--q-bg)",
    probe: "background of a `*-box`, `*-card`, `*-panel` or `*-surface` class",
    fallback: { note: "bg", derive: (get) => get("bg") },
  },
  {
    key: "elevated",
    target: "--q-elevated",
    kind: "color",
    group: "ground",
    names: ["bg-elevated", "surface-elevated", "popover", "bg-overlay"],
    role: "Menus, popovers, dialogs, toasts.",
    perTheme: true,
    default: { light: "#ffffff", dark: "#111827" },
    fallback: {
      note: "card on a light ground, raised on a dark one",
      derive: (get) => (isDark(get) ? get("raised") : get("card")),
    },
  },
  // ---- rules ------------------------------------------------------------------
  {
    key: "hairline",
    target: "--q-hairline",
    kind: "color",
    group: "line",
    names: ["app-line", "line", "border", "hairline", "color-border", "divider"],
    role: "Rules between rows, the edge of a card, control borders.",
    perTheme: true,
    default: { light: "#e5e7eb", dark: "#273142" },
    fallback: {
      note: "fg at 25% (20% on a dark ground)",
      derive: (get) => withAlpha(get("fg"), isDark(get) ? 0.2 : 0.25),
    },
  },
  {
    key: "rule",
    target: "--q-rule",
    kind: "color",
    group: "line",
    names: ["app-action", "line-strong", "border-strong", "rule", "color-border-strong"],
    role: "The rule under a table header, the top rule of a list.",
    perTheme: true,
    default: { light: "#374151", dark: "#f9fafb" },
    fallback: { note: "fg", derive: (get) => get("fg") },
  },
  // ---- action -----------------------------------------------------------------
  {
    key: "action",
    target: "--q-action",
    kind: "color",
    group: "action",
    names: ["app-action", "action", "primary", "accent", "brand", "color-primary"],
    role: "The primary button.",
    perTheme: true,
    default: { light: "#374151", dark: "#f9fafb" },
    fallback: { note: "fg", derive: (get) => get("fg") },
  },
  {
    key: "on-action",
    target: "--q-on-action",
    kind: "color",
    group: "action",
    names: ["app-on-action", "on-action", "on-primary", "primary-foreground", "on-accent", "action-fg"],
    role: "Text and marks on the action fill.",
    perTheme: true,
    default: { light: "#ffffff", dark: "#030712" },
    fallback: { note: "bg", derive: (get) => get("bg") },
  },
  {
    key: "action-hover",
    target: "--q-action-hover",
    kind: "color",
    group: "action",
    names: ["action-hover", "primary-hover", "accent-hover"],
    role: "The action fill under the pointer.",
    perTheme: true,
    default: { light: "#4b5563", dark: "#e5e7eb" },
    fallback: { note: "action mixed 85% into bg", derive: (get) => mix(get("action"), get("bg"), 0.85) },
  },
  // ---- signal ---------------------------------------------------------------
  {
    key: "signal",
    target: "--q-signal",
    kind: "color",
    group: "signal",
    names: ["app-signal", "signal", "link", "color-link", "selection"],
    role: "The one hue, for state: a checked box, progress, a link.",
    perTheme: true,
    default: { light: "#3b5a86", dark: "#a7bbdc" },
    fallback: { note: "action", derive: (get) => get("action") },
  },
  {
    key: "on-signal",
    target: "--q-on-signal",
    kind: "color",
    group: "signal",
    names: ["app-on-signal", "on-signal", "on-link"],
    role: "The check mark and text on a signal fill.",
    perTheme: true,
    default: { light: "#ffffff", dark: "#111827" },
    fallback: { note: "bg", derive: (get) => get("bg") },
  },
  {
    key: "signal-inverse",
    target: "--q-signal-inverse",
    kind: "color",
    group: "signal",
    names: ["app-signal-inverse", "signal-inverse", "link-inverse"],
    role: "The signal on a dark ground: a link in a toast.",
    perTheme: true,
    default: { light: "#c9d6ec", dark: "#a7bbdc" },
    // The overlay falls back to fg, so the signal has to move towards bg to
    // read on it — whichever way bg is.
    fallback: { note: "signal mixed 30% into bg", derive: (get) => mix(get("signal"), get("bg"), 0.3) },
  },
  {
    key: "selected",
    target: "--q-selected",
    kind: "color",
    group: "signal",
    names: ["app-selected", "selected", "bg-selected", "selection-bg"],
    role: "Selected rows, items and segments.",
    perTheme: true,
    default: { light: "#e6ebf3", dark: "#243149" },
    fallback: { note: "signal mixed 12% into bg", derive: (get) => mix(get("signal"), get("bg"), 0.12) },
  },
  {
    key: "on-selected",
    target: "--q-on-selected",
    kind: "color",
    group: "signal",
    names: ["app-on-selected", "on-selected", "selected-fg"],
    role: "Text in a selected row.",
    perTheme: true,
    default: { light: "#24344f", dark: "#dde6f5" },
    fallback: { note: "fg", derive: (get) => get("fg") },
  },
  // ---- overlay ----------------------------------------------------------------
  {
    key: "overlay",
    target: "--q-overlay",
    kind: "color",
    group: "signal",
    names: ["app-overlay", "overlay", "tooltip", "toast", "inverse-bg"],
    role: "Toasts, tooltips, the selection bar.",
    perTheme: true,
    default: { light: "#374151", dark: "#030712" },
    fallback: { note: "fg", derive: (get) => get("fg") },
  },
  {
    key: "on-overlay",
    target: "--q-on-overlay",
    kind: "color",
    group: "signal",
    names: ["app-on-overlay", "on-overlay", "on-tooltip", "inverse-fg"],
    role: "Text on an overlay.",
    perTheme: true,
    default: { light: "#ffffff", dark: "#f9fafb" },
    fallback: { note: "bg", derive: (get) => get("bg") },
  },
  {
    key: "overlay-ring",
    target: "--q-overlay-ring",
    kind: "color",
    group: "signal",
    names: ["app-overlay-ring", "overlay-ring"],
    role: "The 1px ring around an overlay.",
    perTheme: true,
    default: { light: "#374151", dark: "#374151" },
    fallback: { note: "overlay", derive: (get) => get("overlay") },
  },
  {
    key: "focus",
    target: "--q-focus",
    kind: "color",
    group: "action",
    names: ["app-focus", "app-signal", "focus", "ring", "focus-ring", "color-focus"],
    role: "The focus ring and a focused field's edge.",
    perTheme: true,
    default: { light: "#3b5a86", dark: "#a7bbdc" },
    fallback: { note: "signal", derive: (get) => get("signal") },
  },
  // ---- state --------------------------------------------------------------------
  {
    key: "danger",
    target: "--q-danger",
    kind: "color",
    group: "state",
    names: ["app-danger", "danger", "error", "destructive", "color-danger", "color-error"],
    role: "Invalid fields, destructive actions.",
    perTheme: true,
    default: { light: "#b91c1c", dark: "#fca5a5" },
  },
  {
    key: "warn",
    target: "--q-warn",
    kind: "color",
    group: "state",
    names: ["app-warning", "warn", "warning", "color-warning"],
    role: "Warnings.",
    perTheme: true,
    default: { light: "#92400e", dark: "#fbbf24" },
  },
  {
    key: "success",
    target: "--q-success",
    kind: "color",
    group: "state",
    names: ["app-success", "success", "positive", "color-success"],
    role: "Success states.",
    perTheme: true,
    default: { light: "#065f46", dark: "#4ade80" },
  },
  // ---- stage --------------------------------------------------------------------
  {
    key: "glyph",
    target: "--q-glyph",
    kind: "color",
    group: "stage",
    names: ["glyph", "watermark"],
    role: "The giant watermark mark behind a Stage.",
    perTheme: true,
    default: { light: "#0307120f", dark: "#ffffff12" },
    fallback: { note: "fg at 6%", derive: (get) => withAlpha(get("fg"), 0.06) },
  },
  {
    key: "glow-from",
    target: "--q-glow-from",
    kind: "color",
    group: "stage",
    names: ["glow-from", "stage-from", "hero-from"],
    role: "Where the Stage light starts (top right).",
    perTheme: true,
    default: { light: "#ffffff", dark: "#1f2937" },
    fallback: { note: "bg", derive: (get) => get("bg") },
  },
  {
    key: "glow-to",
    target: "--q-glow-to",
    kind: "color",
    group: "stage",
    names: ["glow-to", "stage-to", "hero-to"],
    role: "Where the Stage light falls off.",
    perTheme: true,
    default: { light: "#d9dce1", dark: "#030712" },
    fallback: { note: "pressed", derive: (get) => get("pressed") },
  },
  {
    key: "page-image",
    target: "--q-page-image",
    kind: "image",
    group: "stage",
    names: ["page-image", "page-pattern", "bg-pattern"],
    role: "A pattern behind the page, such as a dot grid.",
    perTheme: true,
    default: "none",
    probe: "background-image of a `*-page` class",
  },
  {
    key: "page-image-size",
    target: "--q-page-image-size",
    kind: "length",
    group: "stage",
    names: ["page-image-size", "page-pattern-size"],
    role: "The tile size of that pattern.",
    perTheme: false,
    default: "auto",
    probe: "background-size of a `*-page` class",
  },
  ...SHAPE_AND_TYPE_TOKENS,
]

export const TOKEN_BY_KEY: Record<string, TokenSpec> = Object.fromEntries(TOKENS.map((t) => [t.key, t]))

export const GROUP_LABEL: Record<TokenSpec["group"], string> = {
  ground: "grounds",
  ink: "ink",
  line: "rules",
  action: "action & focus",
  signal: "signal & overlay",
  state: "state",
  stage: "stage & page",
  shape: "shape",
  type: "type",
}

/** How a dark theme is recognised, for the page to print. */
export const DARK_SELECTORS = [
  '[data-theme="dark"]',
  ".dark",
  '[data-mode="dark"]',
  "@media (prefers-color-scheme: dark)",
]
