/**
 * The theme import's contract: every token the library paints with, the
 * custom-property names that fill it in an uploaded design system, and how a
 * missing one is derived. The /theme page renders this list as its "what the
 * file must define" table, so editing it edits the instructions too.
 */
import { type Lookup, luminance, mix, type TokenSpec, withAlpha } from "@/site/theme-color"


const isDark = (get: Lookup) => luminance(get("bg")) < 0.2

export const TOKENS: TokenSpec[] = [
  {
    key: "bg",
    target: "--q-bg",
    kind: "color",
    names: ["bg-000", "bg", "background", "color-bg", "color-background", "surface", "page"],
    role: "Page ground. Everything sits on it.",
    required: true,
    perTheme: true,
  },
  {
    key: "fg",
    target: "--q-fg",
    kind: "color",
    names: ["text", "fg", "foreground", "color-text", "color-fg", "ink"],
    role: "Headlines, navigation, links, primary copy.",
    required: true,
    perTheme: true,
  },
  {
    key: "fg-muted",
    target: "--q-fg-muted",
    kind: "color",
    names: ["text-body", "fg-muted", "text-secondary", "color-text-secondary", "body"],
    role: "Running text.",
    perTheme: true,
    fallback: { note: "fg", derive: (get) => get("fg") },
  },
  {
    key: "fg-subtle",
    target: "--q-fg-subtle",
    kind: "color",
    names: ["text-muted", "fg-subtle", "text-tertiary", "muted", "color-text-muted"],
    role: "Labels, captions, numbers, placeholders.",
    perTheme: true,
    fallback: { note: "fg mixed 68% into bg", derive: (get) => mix(get("fg"), get("bg"), 0.68) },
  },
  {
    key: "raised",
    target: "--q-raised",
    kind: "color",
    names: ["bg-100", "bg-raised", "surface-raised", "bg-subtle", "surface-2"],
    role: "Hovered rows, tags, inset areas.",
    perTheme: true,
    fallback: { note: "fg mixed 10% into bg", derive: (get) => mix(get("fg"), get("bg"), 0.1) },
  },
  {
    key: "pressed",
    target: "--q-pressed",
    kind: "color",
    names: ["bg-200", "bg-pressed", "surface-pressed", "bg-selected", "surface-3"],
    role: "Pressed states, selected rows.",
    perTheme: true,
    fallback: { note: "fg mixed 15% into bg", derive: (get) => mix(get("fg"), get("bg"), 0.15) },
  },
  {
    key: "elevated",
    target: "--q-elevated",
    kind: "color",
    names: ["bg-elevated", "surface-elevated", "popover", "bg-overlay"],
    role: "Menus, popovers, dialogs, toasts.",
    perTheme: true,
    fallback: {
      note: "bg on a light ground, raised on a dark one",
      derive: (get) => (isDark(get) ? get("raised") : get("bg")),
    },
  },
  {
    key: "hairline",
    target: "--q-hairline",
    kind: "color",
    names: ["line", "border", "hairline", "color-border", "divider"],
    role: "Hairline rules between rows, around cards, under the nav.",
    perTheme: true,
    fallback: {
      note: "fg at 25% (20% on a dark ground)",
      derive: (get) => withAlpha(get("fg"), isDark(get) ? 0.2 : 0.25),
    },
  },
  {
    key: "rule",
    target: "--q-rule",
    kind: "color",
    names: ["line-strong", "border-strong", "rule", "color-border-strong"],
    role: "Control borders, input underlines, the top rule of a table.",
    perTheme: true,
    fallback: { note: "fg", derive: (get) => get("fg") },
  },
  {
    key: "action",
    target: "--q-action",
    kind: "color",
    names: ["action", "primary", "accent", "brand", "color-primary"],
    role: "The solid button, a checked box, a selected day.",
    perTheme: true,
    fallback: { note: "fg", derive: (get) => get("fg") },
  },
  {
    key: "on-action",
    target: "--q-on-action",
    kind: "color",
    names: ["on-action", "on-primary", "primary-foreground", "on-accent", "action-fg"],
    role: "Text and marks on the action fill.",
    perTheme: true,
    fallback: { note: "bg", derive: (get) => get("bg") },
  },
  {
    key: "action-hover",
    target: "--q-action-hover",
    kind: "color",
    names: ["action-hover", "primary-hover", "accent-hover"],
    role: "The action fill under the pointer.",
    perTheme: true,
    fallback: { note: "action mixed 85% into bg", derive: (get) => mix(get("action"), get("bg"), 0.85) },
  },
  {
    key: "focus",
    target: "--q-focus",
    kind: "color",
    names: ["focus", "ring", "focus-ring", "color-focus"],
    role: "The focus ring and a focused input's underline.",
    perTheme: true,
    fallback: { note: "action", derive: (get) => get("action") },
  },
  {
    key: "glyph",
    target: "--q-glyph",
    kind: "color",
    names: ["glyph", "watermark"],
    role: "The giant watermark mark behind a Stage.",
    perTheme: true,
    fallback: { note: "fg at 6%", derive: (get) => withAlpha(get("fg"), 0.06) },
  },
  {
    key: "glow-from",
    target: "--q-glow-from",
    kind: "color",
    names: ["glow-from", "stage-from", "hero-from"],
    role: "Where the Stage light starts (top right).",
    perTheme: true,
    fallback: { note: "bg", derive: (get) => get("bg") },
  },
  {
    key: "glow-to",
    target: "--q-glow-to",
    kind: "color",
    names: ["glow-to", "stage-to", "hero-to"],
    role: "Where the Stage light falls off.",
    perTheme: true,
    fallback: { note: "pressed", derive: (get) => get("pressed") },
  },
  {
    key: "danger",
    target: "--q-danger",
    kind: "color",
    names: ["danger", "error", "destructive", "color-danger", "color-error"],
    role: "Invalid fields, destructive actions.",
    perTheme: true,
  },
  {
    key: "warn",
    target: "--q-warn",
    kind: "color",
    names: ["warn", "warning", "color-warning"],
    role: "Warnings.",
    perTheme: true,
  },
  {
    key: "success",
    target: "--q-success",
    kind: "color",
    names: ["success", "positive", "color-success"],
    role: "Success states.",
    perTheme: true,
  },
  {
    key: "shadow-float",
    target: "--q-shadow-float",
    kind: "shadow",
    names: ["shadow-float", "shadow-popover", "shadow-overlay", "shadow-lg"],
    role: "The one shadow: floating surfaces only.",
    perTheme: true,
  },
  {
    key: "font-display",
    target: "--font-display",
    kind: "font",
    names: ["font-display", "font-heading", "font-headline", "font-serif"],
    role: "Headlines, titles, navigation.",
    perTheme: false,
  },
  {
    key: "font-text",
    target: "--font-sans",
    kind: "font",
    names: ["font-text", "font-sans", "font-body", "font-base"],
    role: "Running text, controls, buttons.",
    perTheme: false,
  },
  {
    key: "font-mono",
    target: "--font-mono",
    kind: "font",
    names: ["font-mono", "font-code"],
    role: "Labels and code.",
    perTheme: false,
  },
  {
    key: "radius-s",
    target: "--radius-quebi-s",
    kind: "length",
    names: ["radius-s", "radius-sm", "radius-small"],
    role: "Tooltips, menus, popovers.",
    perTheme: false,
  },
  {
    key: "radius-l",
    target: "--radius-quebi-l",
    kind: "length",
    names: ["radius-l", "radius-lg", "radius-large"],
    role: "The frame of an embedded Stage.",
    perTheme: false,
  },
]

/** How a dark theme is recognised, for the page to print. */
export const DARK_SELECTORS = [
  '[data-theme="dark"]',
  ".dark",
  '[data-mode="dark"]',
  "@media (prefers-color-scheme: dark)",
]

