/**
 * The shape and type half of the theme contract in `theme-tokens.ts`: radii,
 * borders, the field frame, shadows and the four faces. Split out only to keep
 * either file readable; `TOKENS` lists these after the colours, in this order.
 */
import type { TokenSpec } from "@/site/theme-color"

const NO_SHADOW = "none"

export const SHAPE_AND_TYPE_TOKENS: TokenSpec[] = [
  // ---- shape --------------------------------------------------------------------
  {
    key: "radius-control",
    target: "--q-radius-control",
    kind: "length",
    group: "shape",
    names: ["app-radius", "radius-control", "radius-button", "radius-input", "radius-m", "radius-md"],
    role: "Corners of buttons, fields and toggles.",
    perTheme: false,
    default: "6px",
    probe: "border-radius of a `*-btn` / `*-button` class",
  },
  {
    key: "radius-surface",
    target: "--q-radius-surface",
    kind: "length",
    group: "shape",
    names: ["app-radius-l", "radius-surface", "radius-card", "radius-box"],
    role: "Corners of cards and dialogs.",
    perTheme: false,
    default: "10px",
    probe: "border-radius of a `*-box` / `*-card` class",
  },
  {
    key: "radius-mark",
    target: "--q-radius-mark",
    kind: "length",
    group: "shape",
    names: ["app-radius-s", "radius-mark", "radius-checkbox"],
    role: "Corners of the checkbox box, badges, tooltips.",
    perTheme: false,
    default: "4px",
    probe: "border-radius of the input in a `*-check` / `*-checkbox` class",
  },
  {
    key: "radius-s",
    target: "--radius-quebi-s",
    kind: "length",
    group: "shape",
    names: ["radius-s", "radius-sm", "radius-small"],
    role: "Corners of tooltips, menus, popovers.",
    perTheme: false,
    default: "6px",
  },
  {
    key: "radius-l",
    target: "--radius-quebi-l",
    kind: "length",
    group: "shape",
    names: ["radius-l", "radius-lg", "radius-large"],
    role: "The frame of an embedded Stage.",
    perTheme: false,
    default: "22px",
  },
  {
    key: "border-control",
    target: "--q-border-control",
    kind: "length",
    group: "shape",
    names: ["border-control", "border-width-control", "border-width"],
    role: "Border width of buttons, fields and checkboxes.",
    perTheme: false,
    default: "1px",
    probe: "border width of a `*-btn` / `*-button` class",
  },
  {
    key: "border-surface",
    target: "--q-border-surface",
    kind: "length",
    group: "shape",
    names: ["border-surface", "border-width-surface", "border-card"],
    role: "Border width of cards.",
    perTheme: false,
    default: "1px",
    probe: "border width of a `*-box` / `*-card` class",
  },
  {
    key: "field",
    target: "--q-field-*",
    kind: "choice",
    group: "shape",
    names: ["field-style"],
    role: "Fields as an underline, or as a box on the card ground.",
    perTheme: false,
    default: "box",
    choices: ["underline", "box"],
    probe: "an `*-input` class (or `*-field input`) with side borders is a box",
  },
  {
    key: "field-px",
    target: "--q-field-px",
    kind: "length",
    group: "shape",
    names: ["field-padding", "input-padding-x"],
    role: "Inline padding inside a boxed field.",
    perTheme: false,
    default: "12px",
    probe: "padding-left of that input",
  },
  {
    key: "press",
    target: "--q-press",
    kind: "length",
    group: "shape",
    names: ["press", "press-offset"],
    role: "How far a button travels into its shadow on hover and press.",
    perTheme: false,
    default: "0px",
    probe: "translate on `*-btn:hover` / `:active`",
  },
  {
    key: "shadow-control",
    target: "--q-shadow-control",
    kind: "shadow",
    group: "shape",
    names: ["shadow-control", "shadow-button", "shadow-input"],
    role: "Shadow of outline buttons, fields and toggles.",
    perTheme: true,
    default: NO_SHADOW,
    probe: "box-shadow of a `*-btn` class",
  },
  {
    key: "shadow-action",
    target: "--q-shadow-action",
    kind: "shadow",
    group: "shape",
    names: ["shadow-action", "shadow-solid", "shadow-primary"],
    role: "Shadow of the solid button.",
    perTheme: true,
    default: NO_SHADOW,
    probe: "box-shadow of a `*-btn-solid` / `*-btn-primary` class",
  },
  {
    key: "shadow-surface",
    target: "--q-shadow-surface",
    kind: "shadow",
    group: "shape",
    names: ["shadow-surface", "shadow-card", "shadow-box", "shadow-hard"],
    role: "Shadow of cards.",
    perTheme: true,
    default: NO_SHADOW,
    probe: "box-shadow of a `*-box` / `*-card` class",
  },
  {
    key: "shadow-overlay",
    target: "--q-shadow-overlay",
    kind: "shadow",
    group: "shape",
    names: ["app-shadow-overlay", "shadow-overlay-ring"],
    role: "Shadow of toasts, tooltips, the selection bar.",
    perTheme: true,
    default: {
      light: "0 0 0 1px #374151, 0 12px 32px #03071240",
      dark: "0 0 0 1px #374151, 0 12px 32px #00000099",
    },
  },
  {
    key: "shadow-float",
    target: "--q-shadow-float",
    kind: "shadow",
    group: "shape",
    names: ["shadow-float", "shadow-popover", "shadow-overlay", "shadow-lg"],
    role: "Shadow of menus, popovers, dialogs, toasts.",
    perTheme: true,
    default: {
      light: "0 1px 2px #0307120f, 0 12px 32px #03071214",
      dark: "0 0 0 1px #ffffff1a, 0 12px 32px #00000099",
    },
  },
  // ---- type ---------------------------------------------------------------------
  {
    key: "font-display",
    target: "--font-display",
    kind: "font",
    group: "type",
    names: ["font-display", "font-heading", "font-headline", "font-serif"],
    role: "Headlines, titles, navigation.",
    perTheme: false,
    default: '"Outfit", ui-sans-serif, system-ui, sans-serif',
  },
  {
    key: "font-text",
    target: "--font-sans",
    kind: "font",
    group: "type",
    names: ["font-text", "font-sans", "font-body", "font-base"],
    role: "Running text and fields.",
    perTheme: false,
    default: '"Inter", ui-sans-serif, system-ui, sans-serif',
  },
  {
    key: "font-mono",
    target: "--font-mono",
    kind: "font",
    group: "type",
    names: ["font-mono", "font-code"],
    role: "Labels and code.",
    perTheme: false,
    default: '"JetBrains Mono", ui-monospace, "SF Mono", Menlo, monospace',
  },
  {
    key: "font-control",
    target: "--q-font-control",
    kind: "font",
    group: "type",
    names: ["font-control", "font-button"],
    role: "The face of buttons, toggles and tags.",
    perTheme: false,
    default: "var(--font-sans)",
    probe: "font-family of a `*-btn` class",
  },
]
