/**
 * The theme contract: every token the library paints with, its Ink & Paper
 * default, the custom-property names that fill it in an uploaded design
 * system, the component it is read from when no name matches, and how a
 * missing colour is derived. The /theme page renders this list as its "what
 * the file must define" table and builds its editor from it, so editing it
 * edits both. `tests/theme-import.test.ts` checks every default against
 * quebi-theme.css.
 */
import { type Lookup, luminance, mix, type TokenSpec, withAlpha } from "@/site/theme-color"

const isDark = (get: Lookup) => luminance(get("bg")) < 0.2

const NO_SHADOW = "none"

export const TOKENS: TokenSpec[] = [
  // ---- grounds --------------------------------------------------------------
  {
    key: "bg",
    target: "--q-bg",
    kind: "color",
    group: "ground",
    names: ["bg-000", "bg", "background", "color-bg", "color-background", "surface", "page"],
    role: "Page ground. Everything sits on it.",
    required: true,
    perTheme: true,
    default: { light: "#ffffff", dark: "#030712" },
    probe: "background of a `*-page` class",
  },
  {
    key: "fg",
    target: "--q-fg",
    kind: "color",
    group: "ink",
    names: ["text", "fg", "foreground", "color-text", "color-fg", "ink"],
    role: "Headlines, navigation, links, primary copy.",
    required: true,
    perTheme: true,
    default: { light: "#030712", dark: "#f9fafb" },
  },
  {
    key: "fg-muted",
    target: "--q-fg-muted",
    kind: "color",
    group: "ink",
    names: ["text-body", "fg-muted", "text-secondary", "color-text-secondary", "body"],
    role: "Running text.",
    perTheme: true,
    default: { light: "#1f2937", dark: "#d1d5db" },
    fallback: { note: "fg", derive: (get) => get("fg") },
  },
  {
    key: "fg-subtle",
    target: "--q-fg-subtle",
    kind: "color",
    group: "ink",
    names: ["text-muted", "fg-subtle", "text-tertiary", "muted", "color-text-muted"],
    role: "Labels, captions, numbers, placeholders.",
    perTheme: true,
    default: { light: "#4b5563", dark: "#9ca3af" },
    fallback: { note: "fg mixed 68% into bg", derive: (get) => mix(get("fg"), get("bg"), 0.68) },
  },
  {
    key: "raised",
    target: "--q-raised",
    kind: "color",
    group: "ground",
    names: ["bg-100", "bg-raised", "surface-raised", "bg-subtle", "surface-2"],
    role: "Hovered rows, tags, inset areas.",
    perTheme: true,
    default: { light: "#e5e7eb", dark: "#111827" },
    fallback: { note: "fg mixed 10% into bg", derive: (get) => mix(get("fg"), get("bg"), 0.1) },
  },
  {
    key: "pressed",
    target: "--q-pressed",
    kind: "color",
    group: "ground",
    names: ["bg-200", "bg-pressed", "surface-pressed", "bg-selected", "surface-3"],
    role: "Pressed states, selected rows.",
    perTheme: true,
    default: { light: "#d9dce1", dark: "#1f2937" },
    fallback: { note: "fg mixed 15% into bg", derive: (get) => mix(get("fg"), get("bg"), 0.15) },
  },
  {
    key: "card",
    target: "--q-card",
    kind: "color",
    group: "ground",
    names: ["card", "bg-card", "surface-card", "bg-box"],
    role: "The ground of a card, and of a boxed field.",
    perTheme: true,
    default: "var(--q-bg)",
    probe: "background of a `*-box`, `*-card`, `*-panel` or `*-surface` class",
    fallback: { note: "bg", derive: (get) => get("bg") },
  },
  {
    key: "elevated",
    target: "--q-elevated",
    kind: "color",
    group: "ground",
    names: ["bg-elevated", "surface-elevated", "popover", "bg-overlay"],
    role: "Menus, popovers, dialogs, toasts.",
    perTheme: true,
    default: { light: "#ffffff", dark: "#111827" },
    fallback: {
      note: "card on a light ground, raised on a dark one",
      derive: (get) => (isDark(get) ? get("raised") : get("card")),
    },
  },
  // ---- rules ------------------------------------------------------------------
  {
    key: "hairline",
    target: "--q-hairline",
    kind: "color",
    group: "line",
    names: ["line", "border", "hairline", "color-border", "divider"],
    role: "Rules between rows, the edge of a card.",
    perTheme: true,
    default: { light: "#03071240", dark: "#ffffff33" },
    fallback: {
      note: "fg at 25% (20% on a dark ground)",
      derive: (get) => withAlpha(get("fg"), isDark(get) ? 0.2 : 0.25),
    },
  },
  {
    key: "rule",
    target: "--q-rule",
    kind: "color",
    group: "line",
    names: ["line-strong", "border-strong", "rule", "color-border-strong"],
    role: "Control borders, field underlines, the top rule of a table.",
    perTheme: true,
    default: { light: "#030712", dark: "#f9fafb" },
    fallback: { note: "fg", derive: (get) => get("fg") },
  },
  // ---- action -----------------------------------------------------------------
  {
    key: "action",
    target: "--q-action",
    kind: "color",
    group: "action",
    names: ["action", "primary", "accent", "brand", "color-primary"],
    role: "The solid button, a checked box, a selected day.",
    perTheme: true,
    default: { light: "#030712", dark: "#f9fafb" },
    fallback: { note: "fg", derive: (get) => get("fg") },
  },
  {
    key: "on-action",
    target: "--q-on-action",
    kind: "color",
    group: "action",
    names: ["on-action", "on-primary", "primary-foreground", "on-accent", "action-fg"],
    role: "Text and marks on the action fill.",
    perTheme: true,
    default: { light: "#ffffff", dark: "#030712" },
    fallback: { note: "bg", derive: (get) => get("bg") },
  },
  {
    key: "action-hover",
    target: "--q-action-hover",
    kind: "color",
    group: "action",
    names: ["action-hover", "primary-hover", "accent-hover"],
    role: "The action fill under the pointer.",
    perTheme: true,
    default: { light: "#1f2937", dark: "#d1d5db" },
    fallback: { note: "action mixed 85% into bg", derive: (get) => mix(get("action"), get("bg"), 0.85) },
  },
  {
    key: "focus",
    target: "--q-focus",
    kind: "color",
    group: "action",
    names: ["focus", "ring", "focus-ring", "color-focus"],
    role: "The focus ring and a focused field's line.",
    perTheme: true,
    default: { light: "#030712", dark: "#f9fafb" },
    fallback: { note: "action", derive: (get) => get("action") },
  },
  // ---- state --------------------------------------------------------------------
  {
    key: "danger",
    target: "--q-danger",
    kind: "color",
    group: "state",
    names: ["danger", "error", "destructive", "color-danger", "color-error"],
    role: "Invalid fields, destructive actions.",
    perTheme: true,
    default: { light: "#991b1b", dark: "#f87171" },
  },
  {
    key: "warn",
    target: "--q-warn",
    kind: "color",
    group: "state",
    names: ["warn", "warning", "color-warning"],
    role: "Warnings.",
    perTheme: true,
    default: { light: "#92400e", dark: "#fbbf24" },
  },
  {
    key: "success",
    target: "--q-success",
    kind: "color",
    group: "state",
    names: ["success", "positive", "color-success"],
    role: "Success states.",
    perTheme: true,
    default: { light: "#065f46", dark: "#34d399" },
  },
  // ---- stage --------------------------------------------------------------------
  {
    key: "glyph",
    target: "--q-glyph",
    kind: "color",
    group: "stage",
    names: ["glyph", "watermark"],
    role: "The giant watermark mark behind a Stage.",
    perTheme: true,
    default: { light: "#0307120f", dark: "#ffffff12" },
    fallback: { note: "fg at 6%", derive: (get) => withAlpha(get("fg"), 0.06) },
  },
  {
    key: "glow-from",
    target: "--q-glow-from",
    kind: "color",
    group: "stage",
    names: ["glow-from", "stage-from", "hero-from"],
    role: "Where the Stage light starts (top right).",
    perTheme: true,
    default: { light: "#ffffff", dark: "#1f2937" },
    fallback: { note: "bg", derive: (get) => get("bg") },
  },
  {
    key: "glow-to",
    target: "--q-glow-to",
    kind: "color",
    group: "stage",
    names: ["glow-to", "stage-to", "hero-to"],
    role: "Where the Stage light falls off.",
    perTheme: true,
    default: { light: "#d9dce1", dark: "#030712" },
    fallback: { note: "pressed", derive: (get) => get("pressed") },
  },
  {
    key: "page-image",
    target: "--q-page-image",
    kind: "image",
    group: "stage",
    names: ["page-image", "page-pattern", "bg-pattern"],
    role: "A pattern behind the page, such as a dot grid.",
    perTheme: true,
    default: "none",
    probe: "background-image of a `*-page` class",
  },
  {
    key: "page-image-size",
    target: "--q-page-image-size",
    kind: "length",
    group: "stage",
    names: ["page-image-size", "page-pattern-size"],
    role: "The tile size of that pattern.",
    perTheme: false,
    default: "auto",
    probe: "background-size of a `*-page` class",
  },
  // ---- shape --------------------------------------------------------------------
  {
    key: "radius-control",
    target: "--q-radius-control",
    kind: "length",
    group: "shape",
    names: ["radius-control", "radius-button", "radius-input", "radius-m", "radius-md"],
    role: "Corners of buttons, fields and toggles.",
    perTheme: false,
    default: "0px",
    probe: "border-radius of a `*-btn` / `*-button` class",
  },
  {
    key: "radius-surface",
    target: "--q-radius-surface",
    kind: "length",
    group: "shape",
    names: ["radius-surface", "radius-card", "radius-box"],
    role: "Corners of cards.",
    perTheme: false,
    default: "0px",
    probe: "border-radius of a `*-box` / `*-card` class",
  },
  {
    key: "radius-mark",
    target: "--q-radius-mark",
    kind: "length",
    group: "shape",
    names: ["radius-mark", "radius-checkbox"],
    role: "Corners of the checkbox box.",
    perTheme: false,
    default: "0px",
    probe: "border-radius of the input in a `*-check` / `*-checkbox` class",
  },
  {
    key: "radius-s",
    target: "--radius-quebi-s",
    kind: "length",
    group: "shape",
    names: ["radius-s", "radius-sm", "radius-small"],
    role: "Corners of tooltips, menus, popovers.",
    perTheme: false,
    default: "6px",
  },
  {
    key: "radius-l",
    target: "--radius-quebi-l",
    kind: "length",
    group: "shape",
    names: ["radius-l", "radius-lg", "radius-large"],
    role: "The frame of an embedded Stage.",
    perTheme: false,
    default: "22px",
  },
  {
    key: "border-control",
    target: "--q-border-control",
    kind: "length",
    group: "shape",
    names: ["border-control", "border-width-control", "border-width"],
    role: "Border width of buttons, fields and checkboxes.",
    perTheme: false,
    default: "1px",
    probe: "border width of a `*-btn` / `*-button` class",
  },
  {
    key: "border-surface",
    target: "--q-border-surface",
    kind: "length",
    group: "shape",
    names: ["border-surface", "border-width-surface", "border-card"],
    role: "Border width of cards.",
    perTheme: false,
    default: "1px",
    probe: "border width of a `*-box` / `*-card` class",
  },
  {
    key: "field",
    target: "--q-field-*",
    kind: "choice",
    group: "shape",
    names: ["field-style"],
    role: "Fields as an underline, or as a box on the card ground.",
    perTheme: false,
    default: "underline",
    choices: ["underline", "box"],
    probe: "an `*-input` class (or `*-field input`) with side borders is a box",
  },
  {
    key: "field-px",
    target: "--q-field-px",
    kind: "length",
    group: "shape",
    names: ["field-padding", "input-padding-x"],
    role: "Inline padding inside a boxed field.",
    perTheme: false,
    default: "12px",
    probe: "padding-left of that input",
  },
  {
    key: "press",
    target: "--q-press",
    kind: "length",
    group: "shape",
    names: ["press", "press-offset"],
    role: "How far a button travels into its shadow on hover and press.",
    perTheme: false,
    default: "0px",
    probe: "translate on `*-btn:hover` / `:active`",
  },
  {
    key: "shadow-control",
    target: "--q-shadow-control",
    kind: "shadow",
    group: "shape",
    names: ["shadow-control", "shadow-button", "shadow-input"],
    role: "Shadow of outline buttons, fields and toggles.",
    perTheme: true,
    default: NO_SHADOW,
    probe: "box-shadow of a `*-btn` class",
  },
  {
    key: "shadow-action",
    target: "--q-shadow-action",
    kind: "shadow",
    group: "shape",
    names: ["shadow-action", "shadow-solid", "shadow-primary"],
    role: "Shadow of the solid button.",
    perTheme: true,
    default: NO_SHADOW,
    probe: "box-shadow of a `*-btn-solid` / `*-btn-primary` class",
  },
  {
    key: "shadow-surface",
    target: "--q-shadow-surface",
    kind: "shadow",
    group: "shape",
    names: ["shadow-surface", "shadow-card", "shadow-box", "shadow-hard"],
    role: "Shadow of cards.",
    perTheme: true,
    default: NO_SHADOW,
    probe: "box-shadow of a `*-box` / `*-card` class",
  },
  {
    key: "shadow-float",
    target: "--q-shadow-float",
    kind: "shadow",
    group: "shape",
    names: ["shadow-float", "shadow-popover", "shadow-overlay", "shadow-lg"],
    role: "Shadow of menus, popovers, dialogs, toasts.",
    perTheme: true,
    default: {
      light: "0 1px 2px #0307120f, 0 12px 32px #03071214",
      dark: "0 0 0 1px #ffffff1a, 0 12px 32px #00000099",
    },
  },
  // ---- type ---------------------------------------------------------------------
  {
    key: "font-display",
    target: "--font-display",
    kind: "font",
    group: "type",
    names: ["font-display", "font-heading", "font-headline", "font-serif"],
    role: "Headlines, titles, navigation.",
    perTheme: false,
    default: '"Outfit", ui-sans-serif, system-ui, sans-serif',
  },
  {
    key: "font-text",
    target: "--font-sans",
    kind: "font",
    group: "type",
    names: ["font-text", "font-sans", "font-body", "font-base"],
    role: "Running text and fields.",
    perTheme: false,
    default: '"Inter", ui-sans-serif, system-ui, sans-serif',
  },
  {
    key: "font-mono",
    target: "--font-mono",
    kind: "font",
    group: "type",
    names: ["font-mono", "font-code"],
    role: "Labels and code.",
    perTheme: false,
    default: '"JetBrains Mono", ui-monospace, "SF Mono", Menlo, monospace',
  },
  {
    key: "font-control",
    target: "--q-font-control",
    kind: "font",
    group: "type",
    names: ["font-control", "font-button"],
    role: "The face of buttons, toggles and tags.",
    perTheme: false,
    default: "var(--font-sans)",
    probe: "font-family of a `*-btn` class",
  },
]

export const TOKEN_BY_KEY: Record<string, TokenSpec> = Object.fromEntries(TOKENS.map((t) => [t.key, t]))

export const GROUP_LABEL: Record<TokenSpec["group"], string> = {
  ground: "grounds",
  ink: "ink",
  line: "rules",
  action: "action & focus",
  state: "state",
  stage: "stage & page",
  shape: "shape",
  type: "type",
}

/** How a dark theme is recognised, for the page to print. */
export const DARK_SELECTORS = [
  '[data-theme="dark"]',
  ".dark",
  '[data-mode="dark"]',
  "@media (prefers-color-scheme: dark)",
]
